spring:
  application:
    name: yupao-backend
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/hc
    username: root
    password: 1234
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config: #配置逻辑删除
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段
      logic-delete-value: 1  # 逻辑已删除值 默认为 1
      logic-not-delete-value: 0 # 逻辑未删除值 默认为 0