server:
  port: 8082
  tomcat:
    threads:
      max: 50
    accept-count: 50
    max-connections: 100
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true  # 开启sentinel功能
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商场购物服务接口文档"
    package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # 配置sentinel控制台地址
      http-method-specify: true # 配置是否设置请求方式作为资源名称