---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 风寻.
--- DateTime: 2025/7/25 19:33
---

-- 1 参数列表
--   优惠劵id
local voucherId = ARGV[1]
--  用户id
local userId = ARGV[2]
--订单id
local orderId = ARGV[3]

-- 2 数据key
--     库存key .. 代表 +
local stockKey = 'seckill:stock:' .. voucherId
--     订单key
local orderKey = 'seckill:order:' .. voucherId

-- 3 脚本业务
--     1 判断库存是否足够 tonumber将字符转为数字
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足 返回1
    return 1
end
--     2 判断用户是否已经购买过 SISMEMBER 判断set集合中是否存在某个元素
if(redis.call('sismember', orderKey, userId) == 1) then
    -- 已经购买过 返回2
    return 2
end
--     3 库存减1 incrby -1
redis.call('incrby', stockKey, -1)
--     4 将用户id加入到set集合中
redis.call('sadd', orderKey, userId)
--     5 发送消息到队列当中
redis.call("xadd",'stream.orders','*',"userId",userId,"voucherId",voucherId,"id",orderId)
--     6 返回0 表示成功
return 0