spring.application.name=springboot-pagehelper
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/spring6
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

#mybatis\u914D\u7F6E
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:/mapper/*.xml
